% This file can be used to reproduce all figures in
%?Benning, Celledoni, Ehrhardt, Owren & Schönlieb (2019). 
% Deep learning as optimal control problems: models and 
% numerical methods. http://arxiv.org/abs/1904.05657
filenames = ...
    {'pics/example_donut2d_20layers_backtracking1/ResNet_squared_seed1_video', ...
    'pics/example_donut2d_20layers_backtracking1/ODENetSimplex_squared_seed1_video', ...
    'pics/example_donut2d_20layers_backtracking1/ODENet_squared_seed1_video', ...
    'pics/example_donut2d_20layers_backtracking1/Net_squared_seed1_video', ...
    'pics/example_spiral2d_20layers_backtracking1/ResNet_squared_seed1_video', ...
    'pics/example_spiral2d_20layers_backtracking1/ODENetSimplex_squared_seed1_video', ...
    'pics/example_spiral2d_20layers_backtracking1/ODENet_squared_seed1_video', ...
    'pics/example_spiral2d_20layers_backtracking1/Net_squared_seed1_video'};

for filename = filenames
    v = VideoReader([filename{1}, '.mp4']);
    video = read(v);
    
    for i = 1 : size(video, 4)
        [filename{1}, sprintf('_%02d.png', i)]
        imwrite(video(:,:,:,i), ['./', filename{1}, sprintf('_%02d.png', i)])
    end
end